ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]
# appending other urls patterns to the list of urls above
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import *

app_name= 'shop'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('products/', ProductView.as_view(), name='all_products'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='products_detail'),

    path('add_to_art_<int:pro_id>/', AddToCartView.as_view(), name='addtocart'),
    path('user_cart/', UserCartView.as_view(), name='mycart'),
    path('manage_cart/<int:cart_pdt_id>/', ManageCartView.as_view(), name='managecart'),
    path('empty_cart/', EmptyCartView.as_view(), name='emptycart'),

    path('checkout/', CheckoutView.as_view(), name='checkout'),

    path('register/', CustomerRegistrationView.as_view(), name='newUser'),
    path('login/', CustomerLoginView.as_view(), name='login'),
    path('logout/', CustomerLogoutView.as_view(), name='logout'),


    path('profile/', CustomerProfileView.as_view(), name='profile'),
    path('profile/order-<int:pk>/', CustomerOrderDetailView.as_view(), name='order_detail'),

    path('admin_login/', AdminLoginView.as_view(), name='admin_login'),
    path('admin_all_orders/', AdminOrderListView.as_view(), name='all_orders'),
    path('admin_home/', AdminHomeView.as_view(), name='admin_home'),
    path('admin_order/<int:pk>/', AdminOrderDetailView.as_view(), name='admin_order_detail'),
    path('admin_logout/', AdminLogoutView.as_view(), name='admin_logout'),


    path('admin_order_<int:pk>-change/', AdminOrderStatusChangeView.as_view(), name='order_status_change'),


    path('search/', SearchView.as_view(), name='search'),
]

shop/models.py
from typing import Tuple
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
#admin model
class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    image = models.ImageField(upload_to="uploads/admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name =models.CharField(max_length=200)
    address=models.CharField(max_length=200, null=True,blank=True)
    join_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title=models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

class Product(models.Model):
    title=models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image= models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty=models.CharField(max_length=200, null=True, blank=True)
    return_policy=models.CharField(max_length=200, null=True, blank=True)
    view_count=models.PositiveIntegerField(default=0)


    def __str__(self):
        return self.title

class Cart(models.Model):
    customer=models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total_amount = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart:"+str(self.id)

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE) 
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()


    def __str__(self):
        return "Cart:"+str(self.cart.id)+ "CartProduct:"+str(self.id)

#stored in "database", "form"
ORDER_STATUS = (
    ("Order Recieved","Order Recieved"),
    ("Order Processing","Order Processing"),
    ("Order Despatched","Order Despatched"),
    ("Order Complete","Order Complete"),
    ("Order Cancelled","Order Cancelled"),
)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by=models.CharField(max_length=200)
    shipping_address=models.CharField(max_length=200)
    mobile = models.CharField(max_length=15)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order:"+str(self.id)

shop/forms.py
from django import forms
from .models import Customer, Order
from django.contrib.auth.models import User
# angle form
class CheckoutForm(forms.ModelForm):
    class Meta:
        model= Order
        # list of fields that you want to show on the form
        fields = ["ordered_by", "shipping_address","mobile", "email"]

class CustomerRegistrationForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.CharField(widget=forms.EmailInput())
    class Meta:
        model = Customer
        fields = ["username", "password","email","full_name", "address"]
# username validation
    def clean_username(self):
        uname = self.cleaned_data.get("username")
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError("Customer with this username already Exists")

        return uname

class CustomerLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

class AdminLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

shop/views.py
from django.core import paginator
from django.http import request
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login,logout
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from .forms import CheckoutForm, CustomerRegistrationForm,CustomerLoginForm,AdminLoginForm
from .models import Cart, CartProduct, Category, Customer, ORDER_STATUS, Order, Product, Admin
from django.shortcuts import redirect, render
from django.views.generic import View, TemplateView, CreateView, ListView
from django.urls import reverse_lazy

from django.core.paginator import Paginator

from django.db.models import Q #this Q is for a complete search


class EcomMixin(object):
    def dispatch(self, request, *args, **kwargs):
        cart_id = request.session.get("cart_id")
        user = request.user
        #assigning a customer to a cart
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            if user.is_authenticated and user.customer:
                cart_obj.customer = user.customer
                cart_obj.save()

        return super().dispatch(request, *args, **kwargs)
    
# Create your views here.
class HomeView(EcomMixin,TemplateView):
    template_name="shop/index.html"
    # getting all items from the database
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_product = Product.objects.all().order_by('-id')
        
        # number of item to display
        paginator = Paginator(all_product, 4)
        page_number = self.request.GET.get("page")
        product_list = paginator.get_page(page_number)

        # returns all item from the products schema
        context['product_list'] = product_list #showing the latest item
        context['list_cat'] = Category.objects.all()
        return context

# display items by category
class ProductView(EcomMixin,TemplateView):
    template_name="shop/products.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # display categories
        context['list_cat'] = Category.objects.all()
        return context

class ProductDetailView(EcomMixin,TemplateView):
    template_name="shop/product_detail.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slugg = self.kwargs['slug']
        product = Product.objects.get(slug=slugg) #get will fetch only one item
        product.view_count +=1
        product.save()
        context['single_product'] = product
        return context
    
class AddToCartView(EcomMixin,TemplateView):
    template_name="shop/addto_cart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # get product id from requested url
        product_id = self.kwargs['pro_id']
        # get product object for the db
        product_obj = Product.objects.get(id = product_id)
        # check whether the cart Exists or not using sessions
        cart_id = self.request.session.get('cart_id', None)

        if cart_id:
            # if the cart id exist we fetch the cart id
            cart_obj = Cart.objects.get(id=cart_id)
            #using the foriegn key in cart model
            product_in_cart = cart_obj.cartproduct_set.filter(product=product_obj)
            
            if product_in_cart.exists():
                # if items already exist in the cart
                cartproduct = product_in_cart.first()
                # increase the quantity
                cartproduct.quantity += 1
                cartproduct.subtotal += product_obj.selling_price
                cartproduct.save()
                cart_obj.total_amount += product_obj.selling_price
                cart_obj.save()
            else: 
                #if the item in the cart doesn't exist
                cartproduct = CartProduct.objects.create(cart=cart_obj, product=product_obj, 
                        rate=product_obj.selling_price,quantity=1, subtotal=product_obj.selling_price)
                cart_obj.total_amount += product_obj.selling_price
                cart_obj.save()
        else:
            # or we create a new one
            cart_obj = Cart.objects.create(total_amount=0)
            # store the cart id in the sessions
            self.request.session['cart_id'] = cart_obj.id
            cartproduct = CartProduct.objects.create(cart=cart_obj, product=product_obj, 
                        rate=product_obj.selling_price,quantity=1, subtotal=product_obj.selling_price)
            cart_obj.total_amount += product_obj.selling_price
            cart_obj.save()


        # check id the product already exist in the cart

        return context


class UserCartView(EcomMixin,TemplateView):
#sending cart data to the frontend
    template_name="shop/user_cart.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #first get the sessiion cart
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)

        else:
            cart_obj = None
        # display cart items
        context['cartitems'] = cart_obj

        return context

#increase, reduce and delete cart item
class ManageCartView(EcomMixin,View):
    def get(self, request, *args, **kwargs):
        # print("Managing cart items")
        cart_pdt_id = self.kwargs['cart_pdt_id']
        action = request.GET.get('action')
        cart_pdt_obj = CartProduct.objects.get(id=cart_pdt_id) #product object
        cart_item = cart_pdt_obj.cart #cart object
        
        if action == "inc":
            # increasing the quantity of an item in the cart
            cart_pdt_obj.quantity +=1
            cart_pdt_obj.subtotal += cart_pdt_obj.rate
            cart_pdt_obj.save()
            # 
            cart_item.total_amount += cart_pdt_obj.rate
            cart_item.save()
        elif action == "dcr":
            # removing item quantity from the cart
            cart_pdt_obj.quantity -=1
            cart_pdt_obj.subtotal -= cart_pdt_obj.rate
            cart_pdt_obj.save()
            # 
            cart_item.total_amount -= cart_pdt_obj.rate
            cart_item.save()
            # if the quantity is equal to 0, we delete the item from the cart
            if cart_pdt_obj.quantity == 0:
                cart_pdt_obj.delete()

        elif action == "del":
            # we're removing the subtotal from the total amount.
            cart_item.total_amount -= cart_pdt_obj.subtotal
            cart_item.save()
            cart_pdt_obj.delete() #delete the item(product obj) from the cart
        else:
            pass
        # print(cart_pdt_id, action)

        return redirect('shop:mycart')


class EmptyCartView(EcomMixin,View):

    def get(self, request, *args, **kwargs):
        cart_id = request.session.get('cart_id', None)
        if cart_id:
            cart_pdt_obj = Cart.objects.get(id=cart_id)
            cart_pdt_obj.cartproduct_set.all().delete()
            cart_pdt_obj.total_amount=0
            cart_pdt_obj.save()

        
        return redirect('shop:mycart')

class CheckoutView(EcomMixin,CreateView):
    template_name="shop/check_out.html"
    # adding the form class
    form_class = CheckoutForm
    # redirect after successful form submission
    success_url = reverse_lazy('shop:home')
    #to redirect a customer to login in before checking out
    # it's executed before the methods below it. also checks whether the user is logged in or not.
    def dispatch(self, request, *args, **kwargs):
        user = request.user #user currently logged in
        if user.is_authenticated and user.customer:
            pass
        else:
            return redirect("/login/?next=/checkout/")


        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #first get the sessiion cart
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            # get the cart obj
            cart_obj = Cart.objects.get(id=cart_id)
        else:
            cart_obj = None
        # display cart items
        context['cartitems'] = cart_obj

        return context

# filling the rest of the field in the form.
    def form_valid(self, form):
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            # the form instance that is saved into the database.
            form.instance.cart = cart_obj
            form.instance.subtotal = cart_obj.total_amount
            form.instance.discount = 0
            form.instance.total = cart_obj.total_amount
            form.instance.order_status = "Order Recieved"

            del self.request.session['cart_id']

        else:

            return redirect('shop:home')

        return super().form_valid(form)



class CustomerRegistrationView(CreateView):
    template_name = "shop/customer_registration.html"
    form_class = CustomerRegistrationForm
    success_url = reverse_lazy('shop:home')

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")

        user = User.objects.create_user(username, email, password)

        form.instance.user = user
        login(self.request, user)

        return super().form_valid(form)
    
    #to override the success
    def get_success_url(self):
        if "next" in self.request.GET:
            next_url = self.request.GET.get("next")
            return next_url
        else:
            return self.success_url

class CustomerLoginView(FormView):
    template_name = "shop/customer_login.html"
    form_class = CustomerLoginForm
    success_url = reverse_lazy('shop:home')

templates/shop/about.html
{% extends 'shop/base.html' %}
{% block title %}About{% endblock %}
{% block content %}

    <h1>Welcome to About Us</h1>
    {% endblock content %}
        

templates/shop/addto_cart.html
{% extends 'shop/base.html' %}
{% block title %}Add To Cart{% endblock %}
{% block content %}

<div class="container">
<h3>Product added to cart successfully</h3>

</div>
{% endblock content %}
        

templates/shop/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Shop - {% block title %}
        {% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="">
    </head>
    <body>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Shop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:contact' %}">Contact Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:all_products' %}">All Product</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:mycart' %}">Cart</a>
      </li>

      {% if request.user.customer %}
      <li class="nav-item">
        <a class="nav-link">Welcome - {{request.user.username}}! </a></li> 
        <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:logout' %}">LogOut</a> </li> 
        <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:profile' %}">My Profile</a></li> 
        {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:newUser' %}">Register</a> </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:login' %}">Login</a></li>
        {% endif %}
    </ul>
  </div>
</nav>
    {% comment %} <a href="/">Home</a> |
    <a href="{% url 'shop:about' %}">About</a> |
    <a href="{% url 'shop:contact' %}">Contact Us</a> |
    <a href="{% url 'shop:all_products' %}">All Products</a> |
    <a href="{% url 'shop:mycart' %}">Cart</a> |

    {% if request.user.customer %}
    Welcome - {{request.user.username}}! 
    <a href="{% url 'shop:logout' %}">LogOut</a> | 
    <a href="{% url 'shop:profile' %}">My Profile</a>
    {% else %}
    <a href="{% url 'shop:newUser' %}">Register</a> |
    <a href="{% url 'shop:login' %}">Login</a>
    {% endif %} {% endcomment %}
    
    </div>
    
    <div class="container" style="padding:10px; ">
        <div class="row">
            <div class="col-md-4 mx-auto">
                <form action="{% url 'shop:search' %}" class="form-inline" method="GET">
                    <div class="form-group">
                        <label for=""></label>
                        <input type="text" name="keyword" id="" class="form-control" placeholder="Search Product Here..." required>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Search</i></button>
                </form>
    
            </div>
        </div>
    </div>
    {% block  content %}
    {% endblock %}
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
    </body>
</html>

templates/shop/customer_login.html
{% extends 'shop/base.html' %}
{% block title %}User Registration{% endblock %}
{% block content %}
<style>
    .errorlist{
        color:red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
        <h3>User Login Form</h3><hr/>
            <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-info">
                    Customer Login
            </button>
            {% if error %}
                <li class="errorlist">{{error}}</li>
            {% endif %}
            </form>
            <p> Don't have account? Please 
            <a href="{% url 'shop:newUser' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Register here!</a></p>
        </div>
    </div>
</div>
    

{% endblock content %}
        

templates/shop/customer_profile.html
{% extends 'shop/base.html' %}

{% block title %}Customer Profile{% endblock %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-4">
            <h3>Information Details</h3><hr/>
            <p><span class="font-weight-bold">Fullname:</span> {{customer.full_name}}</p>
            <p><span class="font-weight-bold">Username:</span> {{customer.user.username}}</p>
            <p><span class="font-weight-bold">Email:</span> {{customer.user.email}}</p>
            <p><span class="font-weight-bold">Address:</span> {{customer.address}}</p>
            <p><span class="font-weight-bold">joined On:</span> {{customer.join_on}}</p>
            </div>
            <div class="col-md-8">
            <h3>Previous Orders</h3><hr/>
            <table class="table">
                <thead>
                    <tr>
                        <th>sn.</th>
                        <th>Order ID</th>
                        <th>Amount</th>
                        <th>Ordered On</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                {% for order in orders %}
                <tr>
                        <td scope="row">{{forloop.counter}}</td>
                        <td><a href="{% url 'shop:order_detail' order.pk %}">#45753{{order.id}}</a></td>
                        <td>{{order.total}}</td>
                        <td>{{order.created_at}}</td>
                        <td>{{order.order_status}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            </div>
        </div>
    </div>
    {% endblock content %}
        

templates/shop/index.html
{% extends 'shop/base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container">
<h1 class="text-center">Welcome to Shop</h1>
<hr/>
<div class="row mt-4">
    {% for items in product_list %}
    <div class="col-md-3 card"> 
       <div class="mt-3"> 
            <h3><a href="{% url 'shop:products_detail' items.slug %}">{{items.title}}</a></h3>
            <img src="{{items.image.url}}" alt='' class="img-fluid" style="height:200px; object-fit:cover; contain" />
            <br/>
            <p class="mt-3">Price: Shs.<s>{{items.marked_price}}</s> Shs.{{items.selling_price}}</p>
            <a href="{% url 'shop:addtocart' items.id %}" class="btn btn-primary">Add to Cart</a>
        </div>
    </div>
    {% endfor %}
</div>
{% comment %} Pagination {% endcomment %}
<div class="row" style="padding:5px;">
<nav aria-label="...">
  <ul class="pagination">
  {% if product_list.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ product_list.previous_page_number }}">Previous</a>
        </li>
  {% else %}
        <li class="page-item disabled">
        <a class="page-link" href="" tabindex="-1" aria-disabled="true">Previous</a>
        </li>
  {% endif %}
            {% comment %} list {% endcomment %}
            {% for i in product_list.paginator.page_range %}

                {% if i == product_list.number %}
                <li class="page-item active"><a class="page-link">{{i}}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                {% endif %}
            
            
            {% endfor %}
        
    {% if product_list.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ product_list.paginator.num_pages }}">Next</a>
        </li>
    {% else %}
        <li class="page-item" disabled>
        <a class="page-link" href="" tabindex="-1" aria-disabled="true">Next</a>
        </li>
    {% endif %}
  </ul>
</nav></div>
</div>
{% endblock content %}
       

templates/shop/product_search.html
{% extends 'shop/base.html' %}
{% block title %}Search Product{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            <h3>Search Results for <span class="text-info">'{{request.GET.keyword}}'</span></h3>
            <hr/>
            <div class="row mt-4">
            {% for rs in result %}
            <div class="col-md-3 card"> 
                <div class="mt-3"> 
                        <h3><a href="{% url 'shop:products_detail' rs.slug %}">{{rs.title}}</a></h3>
                        <img src="{{rs.image.url}}" alt='' class="img-fluid" style="height:250; object-fit:cover;" />
                        <br/>
                        <p class="mt-3">{{rs.description|truncatewords:10}}</p>
                        <p class="mt-3">Price: Shs.<s>{{rs.marked_price}}</s> Shs.{{rs.selling_price}}</p>
                        <a href="{% url 'shop:addtocart' rs.id %}" class="btn btn-primary">Add to Cart</a>
                    </div>
                </div>
            {% endfor %}
            </div>
            </div>
        </div>    
    </div>
    {% endblock content %}
        

templates/shop/products.html
{% extends 'shop/base.html' %}
{% block title %}All Products{% endblock %}
{% block content %}
<div class="container">

    <h1>All Products</h1>
    <hr/>
    {% for cat in list_cat %}
    <h4>{{cat.title}}</h4>
    <hr/>
    <div class="row">
    {% comment %} reverse | each item under it's category {% endcomment %}
    {% for items in cat.product_set.all  %} 
    {% comment %} product foreign key under cat _set.all {% endcomment %}
    <div class="col-md-3"> 
       <div class="mt-4"> 
            <h3><a href="{% url 'shop:products_detail' items.slug %}">{{items.title}}</a></h3>
            <img src="{{items.image.url}}" alt='' class="img-fluid" style="height:250; object-fit:cover;" />
            <br/>
            <p class="mt-3">Price: Shs.<s>{{items.marked_price}}</s> Shs.{{items.selling_price}}</p>
            <a href="{% url 'shop:addtocart' items.id %}" class="btn btn-primary">Add to Cart</a>
        </div>
    </div>
    {% endfor %}

    </div>
    {% endfor %}
</div>
    {% endblock content %}
        

templates/shop/user_cart.html
{% extends 'shop/base.html' %}
{% block title %}My Cart{% endblock %}
{% block content %}
<div class="container">
    <div class="col-md-8">
    <h4>Items in my Cart.</h4>
    <hr/>
    <table class="table">
        <thead>
            <tr>
                <th>sn.</th>
                <th>Product</th>
                <th>Rate</th>
                <th>Quantity</th>
                <th>Subtotal</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        {% for cart_pdt in cartitems.cartproduct_set.all %}
        <tr>
            <td scope="row">{{forloop.counter}}</td>
            <td>{{cart_pdt.product.title}}</td>
            <td>{{ cart_pdt.rate}}</td>
            <td>{{ cart_pdt.quantity}}</td>
            <td>{{ cart_pdt.subtotal}}</td>
            <td><a href="{% url 'shop:managecart' cart_pdt.id %}?action=inc" class="btn btn-primary">+</a>
            <a href="{% url 'shop:managecart' cart_pdt.id %}?action=dcr" class="btn btn-warning">-</a>
            <a href="{% url 'shop:managecart' cart_pdt.id %}?action=del" class="btn btn-danger">X</a></td>
        </tr>        
        {% endfor %}
        <tr>
            <th colspan="4" class="text-right">Total:</th>
            <th>Shs.{{cartitems.total_amount}}</th>
            {% if cartitems.cartproduct_set.all %}
            <th><a href="{% url 'shop:emptycart' %}">Empty Cart</a></th>
            {% endif %}
            {% if cartitems.cartproduct_set.all %}
            <th><a href="{% url 'shop:checkout' %}" class="btn btn-info">CheckOut</a></th>
            {% endif %}
        </tr>
        
        </tbody>
    </table>

    </div>
</div>
{% endblock content %}
        